import Joi from 'joi';

export const envSchema = Joi.object({
  NODE_ENV: Joi.string().valid('development', 'test', 'production').default('development'),
  PORT: Joi.number().port().default(4000),
  ADMIN_WEB_ORIGIN: Joi.string().uri().required(),
  DATABASE_URL: Joi.string().uri({ scheme: ['postgresql'] }).required(),
  REDIS_URL: Joi.string().uri({ scheme: ['redis', 'rediss'] }).default('redis://localhost:6379'),
  JWT_ACCESS_SECRET: Joi.string().min(32).required(),
  JWT_ACCESS_TTL: Joi.string().default('15m'),
  FIREBASE_PROJECT_ID: Joi.string().allow('').optional(),
  FIREBASE_CLIENT_EMAIL: Joi.string().allow('').optional(),
  FIREBASE_PRIVATE_KEY: Joi.string().allow('').optional(),
  ALLOW_LOCAL_OTP: Joi.boolean().truthy('true').falsy('false').default(false),
  LOCAL_OTP_CODE: Joi.when('ALLOW_LOCAL_OTP', {
    is: true,
    then: Joi.string().pattern(/^\d{6}$/).required(),
    otherwise: Joi.string().allow('').default(''),
  }),
  RAZORPAY_KEY_ID: Joi.string().allow('').optional(),
  RAZORPAY_KEY_SECRET: Joi.string().allow('').optional(),
  RAZORPAY_WEBHOOK_SECRET: Joi.string().min(8).required(),
  ENABLE_TEST_PAYMENT: Joi.boolean().truthy('true').falsy('false').default(false),
  SEED_TEST_DATA: Joi.boolean().truthy('true').falsy('false').default(false),
  GOOGLE_MAPS_API_KEY: Joi.string().allow('').optional(),
  FCM_ENABLED: Joi.boolean().truthy('true').falsy('false').default(false),
  OBJECT_STORAGE_BUCKET: Joi.string().min(3).default('carebook-private'),
  OBJECT_STORAGE_REGION: Joi.string().default('ap-south-1'),
  OBJECT_STORAGE_ENDPOINT: Joi.string().allow('').optional(),
  OBJECT_STORAGE_FORCE_PATH_STYLE: Joi.boolean().truthy('true').falsy('false').default(false),
  OBJECT_STORAGE_ACCESS_KEY: Joi.string().allow('').optional(),
  OBJECT_STORAGE_SECRET_KEY: Joi.string().allow('').optional(),
  OBJECT_STORAGE_KMS_KEY_ID: Joi.string().allow('').optional(),
  DOCUMENT_UPLOAD_URL_TTL_SECONDS: Joi.number().integer().min(60).max(3600).default(600),
  DOCUMENT_DOWNLOAD_URL_TTL_SECONDS: Joi.number().integer().min(30).max(900).default(300),
  DOCUMENT_MAX_SIZE_BYTES: Joi.number().integer().min(1024).max(25_000_000).default(10_485_760),
  APPOINTMENT_HOLD_MINUTES: Joi.number().integer().min(3).max(30).default(10),
  RESCHEDULE_MIN_NOTICE_MINUTES: Joi.number().integer().min(0).max(1440).default(120),
  DEFAULT_TIMEZONE: Joi.string().default('Asia/Kolkata'),
  LOG_LEVEL: Joi.string().valid('fatal', 'error', 'warn', 'info', 'debug', 'trace').default('info'),
});
